version: "3.9"

services:
  api:
    restart: on-failure:5 
    build:
      context: .
    container_name: api
    ports:
      - 5000:5000
    depends_on:
      - mongodb
    environment:
      NODE_ENV: ${NODE_ENV}
    networks:
      - api-network

  mongodb:
    image: mongo:latest
    restart: on-failure:5 
    ports:
      - 27017:27017
    env_file: 
      - .env.credential
    volumes:
      - mongodb-data:/data/db
    networks:
      - api-network

networks:
  api-network:

volumes:
  mongodb-data: